Changed some Tap and TapIf overloads to Check and CheckIf
vkhorikov/CSharpFunctionalExtensions pull request #246
Opened 2020-11-30 11:47 UTC by mingazhev

This is a PR after the issue discussion https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/242.

What was changed:
1. Added Check and CheckIf methods for all Tap and TapIf overloads that could affect output results.
2. Old methods were marked as obsolete and moved to separate files in "Obsolete" folder.
3. Tests were splitted accordingly.

2020-11-30 22:08 UTC, space-alien requested changes
Thanks for the PR! 👍 

Looks good to me, I added a few minor comments.

2020-11-30 22:08 UTC, space-alien commented on CSharpFunctionalExtensions.Tests/ResultTests/Extensions/CheckAsyncBothTests.cs
> +        public void Tap_T_AsyncBoth_func_result(bool resultSuccess, bool funcSuccess)
I think we should rename the Check / CheckIf tests accordingly, for consistency.

2020-11-30 22:08 UTC, space-alien commented on CSharpFunctionalExtensions.Tests/ResultTests/Extensions/CheckAsyncLeftTests.cs
> +    public class CheckAsyncLeftTests : CheckTestsBase
Let's mark this class abstract, for consistency

2020-11-30 22:08 UTC, space-alien commented on CSharpFunctionalExtensions/Result/Obsolete/TapIfAsyncLeft.cs
> +        public static Task<Result<T>> TapIf<T>(this Task<Result<T>> resultTask, bool condition, Func<T, Result> func) =>
Please could you add the [Obsolete] tag as the others.

2020-11-30 22:08 UTC, space-alien commented on CSharpFunctionalExtensions/Result/Obsolete/TapIfAsyncRight.cs
> +        public static Task<Result<T>> TapIf<T>(this Result<T> result, bool condition, Func<T, Task<Result>> func) =>
[Obsolete] tags here too

2020-12-01 09:13 UTC, space-alien approved these changes
Thanks! 👍

2020-12-01 12:49 UTC, merged

2020-12-01 12:54 UTC, vkhorikov commented
Merged, should be available in 2.13.2.